### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by hsvlz** [nandoflorestan/kerno#1]
Hi Nando!

This project looks awesome and seems to be exactly the tooling I need to setup a complex project. Would you have some simple examples of how to use it? (For instance a full example of small flask api with a few components, etc...?)

Cheers,

**Comment by nandoflorestan** [comment]
That's hard. *kerno* is still alpha software, many things are still going to change in it.

But to start with, if you do as much as you can to follow Robert Martin's advice, you are already ahead of more than 90% of Python programmers.

By having a service/action layer and a repository, you sort of save a part of your application from crazy dependencies, of which Flask is very guilty. I hate the fact that in Flask development everything gotta be a Flask plugin... And the plugin for SQLAlchemy that everyone uses is horrible, it tells you to import SQLAlchemy stuff through it, and it adds to models a .query() method, which was removed from SQLAlchemy itself ages ago, and for good architectural reason.

If you can do yourself a favor and start using a truly decoupled web framework such as Pyramid, instead of this Flask mess, that's also good for you. And if you can't because of other people, well, that's life, just do the best you can elsewhere.

You want to know what application I am using to test *kerno* with. That would be *pluserable*, a user registration/login plugin for Pyramid. But most of it is not using kerno yet (this is an old app). Here are the most important bits:

https://github.com/nandoflorestan/pluserable/blob/master/pluserable/data/sqlalchemy/repository.py contains a repository -- a concentration of queries and other SQLAlchemy operations. This is what makes the *actions* unit-testable.

https://github.com/nandoflorestan/pluserable/blob/master/pluserable/actions.py defines a couple of actions using Kerno.

Who calls that? The web controllers, which are called "views" in Pyramid. But beware, kerno is being retrofitted into pluserable, and so far only a couple of views have been converted -- the rest is plain old MVC.

Find the views here: https://github.com/nandoflorestan/pluserable/blob/master/pluserable/views.py

I'll be glad to continue a discussion about software architecture with you.
